name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    steps:
      - uses: docker://monachus/hugo:latest
        run: hugo --cleanDestinationDir --gc
        with:
          name: public
          path: public
  deploy:
    steps:
      - uses: devillex/docker-firebase:slim
        run: firebase deploy --token "$FIREBASE_TOKEN"
        with:
          name: public
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
