name: Build and Deploy

on: [push, pull_request]
branches: [master, netlify-cms]

jobs:
  build:
    uses: monachus/hugo:latest
    steps:
      - run: hugo --cleanDestinationDir --gc
  deploy:
    uses: devillex/docker-firebase:slim
    steps:
      - run: firebase deploy --token "$FIREBASE_TOKEN"
        with:
          path: public
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
