name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: monachus/hugo:latest
    steps:
      - run: hugo --cleanDestinationDir --gc
  deploy:
    runs-on: ubuntu-latest
    container: devillex/docker-firebase:slim
    steps:
      - run: firebase deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
